spring:
  profiles:
    active: test

---
server:
  port: 8200

spring:
  profile: test
  application:
    name: test-cloud-test

---
server:
  port: 8201

spring:
  profile: dev
  application:
    name: test-cloud-dev

