spring:
  profiles:
    active: dev
  application:
    name: test-cloud-dev

server:
  port: 8200

---
spring:
  profile:
    active: test
  application:
    name: test-cloud-test

server:
  port: 8200

